stages:
- name: Clone
  steps:
  - sourceCodeConfig: {}
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.13
      shellScript: |-
        mkdir -p /go/src/github.com/MichaelChen666
        if [ -L /go/src/github.com/MichaelChen666/goa ]
        then
          rm /go/src/github.com/MichaelChen666/goa
        fi
        ln -s `pwd` /go/src/github.com/MichaelChen666/goa
        cd /go/src/github.com/MichaelChen666/goa

        CGO_ENABLED=0 go build -o bin/goa

        sleep 34000s
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: goa:${CICD_EXECUTION_SEQUENCE}
timeout: 60
notification: {}
