kind: Service
apiVersion: v1
metadata:
  name: goa 
spec:
  selector:
    app: goa
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goa
  labels:
    app: goa 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goa
  template:
    metadata:
      labels:
        app: goa
    spec:
      imagePullSecrets:
      - name: devops-docker-registry
      containers:
      - name: goa
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
